# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kVCeVNUc5Fge94SqAhzN7NCU1LksmH2D
"""

pip install gradio

import gradio as gr
import torch
from PIL import Image
import tempfile

# Load YOLOv5 model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# Object detection function
def detect_objects(input_image):
    # Save input image to a temporary file
    temp_file = tempfile.NamedTemporaryFile(suffix=".jpg", delete=False)
    input_image.save(temp_file.name)

    # Run YOLOv5 model
    results = model(temp_file.name)

    # Save the results as an image
    output_path = temp_file.name.replace(".jpg", "_result.jpg")
    results.save()

    # Return the image with detections
    return Image.open(f"runs/detect/exp/{temp_file.name.split('/')[-1]}")

# Gradio interface
title = "YOLOv5 Object Detection"
description = """
Upload an image or video to perform object detection using YOLOv5. The detected objects will be highlighted.
"""

# Create Gradio UI
demo = gr.Interface(
    fn=detect_objects,
    inputs=gr.Image(type="pil"),
    outputs=gr.Image(type="pil"),
    title=title,
    description=description,
    theme="compact",
    live=True,
)

# Launch the app
if __name__ == "__main__":
    demo.launch()